version: "3"
services:
  authorization-service:
    image: ekremozturk/bookend:authorization-ser
    container_name: auth-ser-con
    ports:
      - 9191:9191
    networks:
      - default
  author-service:
    image: ekremozturk/bookend:author-ser
    container_name: author-ser-con
    ports:
      - 8085:8085
    networks:
      - default
  book-service:
    image: ekremozturk/bookend:book-ser
    container_name: book-ser-con
    ports:
      - 8082:8082
    networks:
      - default
  book-club-service:
    image: ekremozturk/bookend:book-club-ser
    container_name: bclub-ser-con
    ports:
      - 8089:8089
    networks:
      - default
  message-service:
    image: ekremozturk/bookend:message-ser
    container_name: message-ser-con
    ports:
      - 8087:8087
    networks:
      - default
  shelf-service:
    image: ekremozturk/bookend:shelf-ser
    container_name: shelf-ser-con
    ports:
      - 8083:8083
    networks:
      - default

  mail-service:
    image: ekremozturk/bookend:mail-ser
    container_name: mail-ser-con
    ports:
      - 8090:8090
    networks:
      - default
  rate-comment-service:
    image: ekremozturk/bookend:rate-comment-ser
    container_name: rate-comment-ser-con
    ports:
      - 8081:8081
    networks:
      - default

  
networks:
  default:
    external: true
