server:
  port: 9191
  error:
    include-message:
spring:
  datasource:
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

kafka:
  endpoint: ${KAFKA_ENDPOINT}
  Port: ${KAFKA_PORT}